language: go
matrix:
  include:
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:masterminds/glide
    packages:
    - glide
install:
  - glide install --force
  - find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} +
  - go build
script:
  - echo "Skip tests..."
after_script:
  - go test -race -v $(glide novendor)
